#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    site_name: 'ETAI'
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'new', icon: 'plus', label: 'Créer' }
            - { name: 'delete', icon: 'close', label: false }
    show:
        actions: ['-edit', '-delete']
    edit:
        actions: ['-delete']
    design:
        color_scheme: 'dark' # dark | light
        brand_color: '#34495e'
        assets:
            css:
            js:
        form_theme: 'vertical'
        templates:
            layout: '/backend/layout.html.twig'
            menu: '/backend/menu.html.twig'
            list: '/backend/list.html.twig'
            show: '/backend/show.html.twig'
        menu:
            - { label: 'Accueil', route: 'accueil', default: true }
            - { label: 'Calendrier', route: 'calendar', icon: 'calendar' }
            - label: 'Transmission'
              icon: 'file'
              children:
                - { label: 'Soins', entity: 'Soin', required_role: ["ROLE_ADMIN", "ROLE_SOIGNANT"] }
                - { label: 'Educatives', entity: 'Educative' }
                - { label: 'Générale', entity: 'Generique', required_role: ["ROLE_ADMIN"] }
            - label: 'Résidents'
              icon: 'users'
              children:
                - { label: 'Présents', entity: 'Residents_actuels'}
                - { label: 'Sortis', entity: 'Residents_passes', required_role: ["ROLE_ADMIN"] }
            - { label: 'Personnel', entity: 'Personnel', icon: 'user', required_role: ["ROLE_ADMIN"] }
            - { label: 'Unités', entity: 'Maisonnee', icon: 'home', required_role: ["ROLE_ADMIN"] }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i'
    list:
        max_results: 20
    entities:
        Personnel:
            class: App\Entity\User
            label: 'Personnel'
            password_encoding: { algorithm: 'bcrypt', cost: 13 }
            show:
                title: 'Fiche Personnel'
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%', label: 'Photo' }
                    #- { property: 'email', label: 'Adresse eMail'}
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - adresse
                    - { property: 'isAdmin', label: 'Administrateur' }
                    - { property: 'isEducateur', label: 'Accompagnant' }
                    - { property: 'isSoignant', label: 'Soignant' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'isActive', label: 'Compte activé' }
            list:
                title: 'Liste du Personnel'
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%', label: 'Photo' }
                    - { property: 'isEducateur', type: 'boolean', label: 'Accompagnant' }
                    - { property: 'isSoignant', type: 'boolean', label: 'Soignant' }
                    #- { property: 'email', type: 'email', label: 'Adresse eMail' }
            form:
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    - { property: 'password', type: 'password', label: 'Mot de Passe' }
                    #- { property: 'password', type: 'password', label: 'Mot de Passe', type_options: { mapped: false } }
                    #- { type: 'divider' }
                    #- { property: 'updated_at', label: 'créé le', type: 'datetime', type_options: { widget: 'choice' } }
                    #- { property: 'password', type: 'repeated', type_options: { first_options: { label: 'Mot de P' }, second_options: { label: 'Confirmer Mot de P' }, required: false } }
                    #- { property: 'email', label: 'Adresse eMail'}
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - adresse
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - { type: 'divider' }
                    - { property: 'isAdmin', label: 'Administrateur' }
                    - { property: 'isEducateur', label: 'Accompagnant' }
                    - { property: 'isSoignant', label: 'Soignant' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { type: 'divider' }
                    - { property: 'isActive', label: 'Compte activé' }

        Residents_actuels:
            label: 'Résidents présents'
            title: 'Résidents présents'
            class: App\Entity\Resident
            show:
                title: 'Fiche Résident'
                fields:
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'isActive', label: 'Résident présent' }
            list:
                title: 'Liste des résidents'
                dql_filter: 'entity.isActive = 1'
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'maisonnee', label: 'Unité' }
            form:
                title: 'Formulaire Résident'
                fields:
                    #- { property: 'createdAt', type: 'birthday', label: 'Résident depuis le' }
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'isActive', type: 'checkbox', label: 'Résident présent' }
                    #- { property: 'password', type: 'repeated', type_options: { first_options: { label: 'Mot de P' }, second_options: { label: 'Confirmer Mot de P' }, required: false } }

        Residents_passes:
            label: 'Résidents sortis'
            class: App\Entity\Resident
            disabled_actions: ['new']
            show:
                title: 'Fiche Résident sorti'
                fields:
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'isActive', label: 'Résident présent' }
            list:
                title: 'Liste des résidents sortis'
                dql_filter: 'entity.isActive = 0'
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'maisonnee', label: 'Unité' }
            form:
                title: 'Formulaire Résident'
                fields:
                    #- { property: 'createdAt', type: 'birthday', label: 'Résident depuis le' }
                    - nom
                    - { property: 'prenom', label: 'Prénom'}
                    - { property: 'description', label: 'Fiche Administrative'}
                    - { property: 'ficheAlimentaire', label: 'Fiche Alimentaire'}
                    - { property: 'ficheMedicale', label: 'Fiche Médicale'}
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'isActive', type: 'checkbox', label: 'Résident présent' }
        Educative:
            class: App\Entity\Transmission
            show:
                title: 'Fiche de Transmission éducative'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'resident', label: 'Résident' }
                    - { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'description', label: 'Contenu Educatif' }
                    - { property: 'alerteSoin', label: 'Alerte Soin', css_class: 'alerteSoin' }
            list:
                title: 'Liste des Transmissions éducatives'
                dql_filter: 'entity.type = 0'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'resident.image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - { property: 'resident', label: 'Résident' }
                    - { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'description', label: 'Contenu Educatif' }
                    - { property: 'alerteSoin', label: 'Alerte Soin' }
            form:
                title: 'Formulaire Transmission éducative'
                fields:
                    - { property: 'createdAt', label: 'Date', css_class: 'date', type_options: { widget: 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': { 'class': 'dateTimePicker' } } }
                    #- { property: 'type', label: 'Type', type: 'choice', type_options: { choices: {'Soin':1, 'Educative':0 } } }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'resident', label: 'Résident' }
                    #- { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'description', label: 'Contenu Educatif' }
                    - { property: 'alerteSoin', label: 'Alerte Soin', css_class: 'alerteSoin' }

        Soin:
            class: App\Entity\Transmission
            show:
                title: 'Fiche de Transmission de soin'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'resident', label: 'Résident' }
                    - { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'description', label: 'Contenu Soin' }
            list:
                title: 'Liste des Transmissions de soins'
                dql_filter: 'entity.type = 1'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'resident.image', type: 'image', base_path: '%app.path.resident_images%', label: 'Photo' }
                    - { property: 'resident', label: 'Résident' }
                    - { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }
                    - { property: 'description', label: 'Contenu soin' }
            form:
                title: 'Formulaire Transmission de soin'
                fields:
                    - { property: 'createdAt', label: 'Date', css_class: 'date', type_options: { widget: 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': { 'class': 'dateTimePicker' } } }
                    #- { property: 'type', label: 'Type', type: 'choice', type_options: { choices: {'Soin':1, 'Educative':0 } } }
                    #- { property: 'name', label: 'Descriptif court' }
                    - { property: 'description', label: 'Contenu Soin' }
                    - { property: 'resident', label: 'Résident' }
                    #- { property: 'user', label: 'Personnel' }
                    - { property: 'maisonnee', label: 'Unité' }

        Generique:
            class: App\Entity\TransmissionGenerique
            show:
                title: 'Fiche de Transmission Générale'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    - { property: 'statut' }
                    - { property: 'message' }
                    - { property: 'maisonnee', label: 'Unité' }
            list:
                title: 'Liste des Transmissions Générales'
                fields:
                    - { property: 'createdAt', label: 'Date' }
                    - { property: 'statut' }
                    - { property: 'message' }
                    - { property: 'maisonnee', label: 'Unité' }
            form:
                title: 'Formulaire Transmission Générale'
                fields:
                    - { property: 'createdAt', label: 'Date', css_class: 'date', type_options: { widget: 'single_text', 'format': 'dd/MM/yyyy H:mm', 'attr': { 'class': 'dateTimePicker' } } }
                    - { property: 'Statut', type: 'choice', type_options: { choices: {'Info':Info, 'Important':Important, 'Urgent':Urgent} } }
                    - { property: 'message' }
                    - { property: 'maisonnee', label: 'Unité' }
        Maisonnee:
            class: App\Entity\Maisonnee
            show:
                title: 'Fiche Unité'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'description', label: 'Descriptif' }
                    - { property: 'users', label: 'Personnel' }
                    - { property: 'residents', label: 'Résidents' }
                    #- { property: 'transmissions', label: 'Transmissions' }

            list:
                title: 'Liste des Unités'
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'users', label: 'Personnel' }
                    - { property: 'residents', label: 'Résidents' }
                    - { property: 'transmissions', label: 'Transmissions' }
            form:
                title: 'Formulaire Unité'
                fields:
                    - { property: 'name', label: 'Nom', type: 'text' }
                    - { property: 'description', label: 'Descriptif' }
