security:
    providers:
        user:
            entity: { class: App\Entity\User, property: email }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      13
        App\Entity\User:
            algorithm: bcrypt
            cost:      13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,  role: ROLE_USER }