#index:
#    path: /
#    defaults: { _controller: 'App\Controller\IndexController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Controller/
    type: annotation

logout:
    path: /logout
